export const cardsActionTypes = {
  OPEN_CARD: "OPEN_CARD",
  OPEN_ALL_CARDS: "OPEN_ALL_CARDS",
  CLOSE_CARD: "CLOSE_CARD",
  SET_ARR_OF_CARDS: "SET_ARR_OF_CARDS",
  SET_CARDS_STATE: "SET_CARDS_STATE",
  SET_MATCH: "SET_MATCH",
};
