export let collection = [
  [2, "diamonds", 0],
  [2, "clubs", 0],
  [2, "hearts", 0],
  [2, "spades", 0],
  [3, "diamonds", 0],
  [3, "clubs", 0],
  [3, "hearts", 0],
  [3, "spades", 0],
  [4, "diamonds", 0],
  [4, "clubs", 0],
  [4, "hearts", 0],
  [4, "spades", 0],
  [5, "diamonds", 0],
  [5, "clubs", 0],
  [5, "hearts", 0],
  [5, "spades", 0],
  [6, "diamonds", 0],
  [6, "clubs", 0],
  [6, "hearts", 0],
  [6, "spades", 0],
  [7, "diamonds", 0],
  [7, "clubs", 0],
  [7, "hearts", 0],
  [7, "spades", 0],
  [8, "diamonds", 0],
  [8, "clubs", 0],
  [8, "hearts", 0],
  [8, "spades", 0],
  [9, "diamonds", 0],
  [9, "clubs", 0],
  [9, "hearts", 0],
  [9, "spades", 0],
  [10, "diamonds", 0],
  [10, "clubs", 0],
  [10, "hearts", 0],
  [10, "spades", 0],
];

export let newCollection = [
  "2-diamonds",
  "2-clubs",
  "2-hearts",
  "2-spades",
  "3-diamonds",
  "3-clubs",
  "3-hearts",
  "3-spades",
  "4-diamonds",
  "4-clubs",
  "4-hearts",
  "4-spades",
  "5-diamonds",
  "5-clubs",
  "5-hearts",
  "5-spades",
  "6-diamonds",
  "6-clubs",
  "6-hearts",
  "6-spades",
  "7-diamonds",
  "7-clubs",
  "7-hearts",
  "7-spades",
  "8-diamonds",
  "8-clubs",
  "8-hearts",
  "8-spades",
  "9-diamonds",
  "9-clubs",
  "9-hearts",
  "9-spades",
];
