export const userActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_DIFFICULTY: "SET_CURRENT_DIFFICULTY",
  INCREASE_NUM_OF_TURNS: "INCREASE_NUM_OF_TURNS",
  RESET_NUM_OF_TURNS: "RESET_NUM_OF_TURNS",
};
